; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wt32-eth01]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.mcu = esp32
board_build.f_cpu = 240000000L

lib_deps = 
    denyssene/SimpleKalmanFilter@^0.1.0

build_flags = 
    -D ARDUINO_ARCH_ESP32
    -D ETH_PHY_TYPE=ETH_PHY_LAN8720
    -D ETH_PHY_ADDR=1
    -D ETH_PHY_MDC=23
    -D ETH_PHY_MDIO=18
    -D ETH_PHY_POWER=16
    -D ETH_CLK_MODE=ETH_CLOCK_GPIO0_IN
